### ISSUE TITLE
Bug: Uncaught SyntaxError: import assertions are not currently supported

### ISSUE THREAD

**Issue by JefvdA** [OwenGranot/2D-RPG-Side-Scroller#16]
When I try to run the game in my browser (firefox 104.0) I get following error message in the console:

`Uncaught SyntaxError: import assertions are not currently supported`

Nothing is being drawn either.

Tried using chrome and then it works fine.

**Comment by GranotOn** [comment]
Seems like importing JSON into modules is in stage 3 and not implemented everywhere yet.

Need to either change format to `.js` and accordingly, or use `fetch` instead of `import`. Likely the latter is better.

Thanks, will close once it's done.

**Comment by GranotOn** [comment]
See #17 . For any follow ups please open a new issue as I am closing this one.
